### ISSUE TITLE
Cocoapods install on El Capitan returns "Unable to find a specification for `Objective-Zip (~> 1.0)"

### ISSUE THREAD

**Issue by kthawkins** [gianlucabertani/Objective-Zip#35]
Cocoapods install on El Capitan returns "Unable to find a specification for `Objective-Zip (~> 1.0)"

cocoapods-0.39.0

pod 'Objective-Zip', '~> 1.0'

**Comment by kthawkins** [comment]
Cocoapods install on El Capitan returns "Unable to find a specification for `Objective-Zip (~> 1.0)"

cocoapods-0.39.0

pod 'Objective-Zip', '~> 1.0'

**Comment by gianlucabertani** [comment]
Fixed the pod name. Sorry about that.

**Comment by kthawkins** [comment]
The problem is still occurring. 
"Unable to find a specification for `Objective-Zip (~> 1.0)"


mac-users-macbook:usseeme macuser$ pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `Objective-Zip (~> 1.0)`
mac-users-macbook:usseeme macuser$ pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `Objective-Zip (~> 1.0)`
mac-users-macbook:usseeme macuser$

**Comment by kthawkins** [comment]
The problem is still occurring.
"Unable to find a specification for `Objective-Zip (~> 1.0)"

mac-users-macbook:usseeme macuser$ pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for Objective-Zip (~> 1.0)
mac-users-macbook:usseeme macuser$ pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for Objective-Zip (~> 1.0)
mac-users-macbook:usseeme macuser$

**Comment by kthawkins** [comment]
Changing pod 'Objective-Zip', '~> 1.0' to 
pod 'objective-zip', '~> 1.0'  works
